[2024-05-14T15:49:54.139+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T15:49:54.180+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflows.check-connection-databases manual__2024-05-14T15:49:51.759290+00:00 [queued]>
[2024-05-14T15:49:54.197+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflows.check-connection-databases manual__2024-05-14T15:49:51.759290+00:00 [queued]>
[2024-05-14T15:49:54.198+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-14T15:49:54.227+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check-connection-databases> on 2024-05-14 15:49:51.759290+00:00
[2024-05-14T15:49:54.237+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2559) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-14T15:49:54.239+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '***s', 'check-connection-databases', 'manual__2024-05-14T15:49:51.759290+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpr4gtfmw7']
[2024-05-14T15:49:54.240+0000] {standard_task_runner.py:63} INFO - Started process 2560 to run task
[2024-05-14T15:49:54.241+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask check-connection-databases
[2024-05-14T15:49:54.304+0000] {task_command.py:426} INFO - Running <TaskInstance: airflows.check-connection-databases manual__2024-05-14T15:49:51.759290+00:00 [running]> on host b549aff647a2
[2024-05-14T15:49:54.454+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***s' AIRFLOW_CTX_TASK_ID='check-connection-databases' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T15:49:51.759290+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-14T15:49:51.759290+00:00'
[2024-05-14T15:49:54.456+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T15:49:54.488+0000] {base.py:84} INFO - Using connection ID 'PostgreSQL' for task execution.
[2024-05-14T15:49:54.638+0000] {python.py:237} INFO - Done. Returned value was: [('PostgreSQL 15.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit',)]
[2024-05-14T15:49:54.639+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T15:49:54.676+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=***s, task_id=check-connection-databases, run_id=manual__2024-05-14T15:49:51.759290+00:00, execution_date=20240514T154951, start_date=20240514T154954, end_date=20240514T154954
[2024-05-14T15:49:54.738+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-14T15:49:54.772+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-14T15:49:54.775+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
